"""create account table

Revision ID: 2d7d5806945b
Revises: 1b5e21b39e7a
Create Date: 2024-03-20 16:22:46.799468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2d7d5806945b'
down_revision: Union[str, None] = '1b5e21b39e7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_type', sa.String(length=255), nullable=False),
    sa.Column('sms_credit', sa.Float(), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_details_id'), 'user_details', ['id'], unique=False)
    op.drop_column('users', 'user_type')
    op.drop_column('users', 'status')
    op.drop_column('users', 'sms_credit')
    op.drop_column('users', 'rate')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rate', mysql.FLOAT(), nullable=True))
    op.add_column('users', sa.Column('sms_credit', mysql.FLOAT(), nullable=True))
    op.add_column('users', sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('user_type', mysql.VARCHAR(length=255), nullable=False))
    op.drop_index(op.f('ix_user_details_id'), table_name='user_details')
    op.drop_table('user_details')
    # ### end Alembic commands ###
