"""empty message

Revision ID: 3fb6dcfc8e9b
Revises: 381d7c3cf72b
Create Date: 2024-05-16 17:54:36.168460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fb6dcfc8e9b'
down_revision: Union[str, None] = '381d7c3cf72b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batch_contacts', sa.Column('sms_credit_reduction', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('batch_contacts', 'sms_credit_reduction')
    # ### end Alembic commands ###
