"""empty message

Revision ID: 9ac35143f999
Revises: d73398837969
Create Date: 2024-04-16 13:10:08.568169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9ac35143f999'
down_revision: Union[str, None] = 'd73398837969'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('transaction_code', sa.String(length=255), nullable=False))
    op.drop_column('transactions', 'transaction_uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('transaction_uuid', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('transactions', 'transaction_code')
    # ### end Alembic commands ###
