"""empty message

Revision ID: c5f22472e9b4
Revises: 3fb6dcfc8e9b
Create Date: 2024-05-16 17:59:30.011275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c5f22472e9b4'
down_revision: Union[str, None] = '3fb6dcfc8e9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('batch_contacts', 'sms_credit_reduction')
    op.add_column('sms_batch', sa.Column('sms_credit_reduction', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sms_batch', 'sms_credit_reduction')
    op.add_column('batch_contacts', sa.Column('sms_credit_reduction', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
