"""empty message

Revision ID: f391f1c904f1
Revises: c34a8dd136ea
Create Date: 2024-04-16 13:04:09.273243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f391f1c904f1'
down_revision: Union[str, None] = 'c34a8dd136ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_modes', sa.Column('transaction_uuid', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_modes', 'transaction_uuid')
    # ### end Alembic commands ###
